services:
  - type: web
    name: tebex-real-links-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: TEBEX_PUBLIC_TOKEN
        sync: false
      - key: TEBEX_PRIVATE_KEY
        sync: false
      - key: TEBEX_STORE_IDENTIFIER
        sync: false
      - key: PACKAGE_ID
        sync: false
